[package]
name = "new-iced-editor"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "highlighter", "debug"] }

rfd = "0.15.3"
tokio = { version = "1.44.2", features = ["full"] }
